name: appteste
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  search_widget: ^1.0.2
  http: ^0.12.2
  animated_text_kit: ^2.2.0
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2
  flappy_search_bar: 1.4.1
  sqflite: ^1.1.3
  path_provider: ^1.1.0
  
  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  
  uses-material-design: true

  assets:
    -  imagens/download.png
    -  imagens/pokemon2.png



